name: linter

on:
  pull_request:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: PHP syntax checker 7.4
        uses: prestashop/github-action-php-lint/7.4@v1
      - name: PHP syntax checker 8.0
        uses: prestashop/github-action-php-lint/8.0@v1
      - name: PHP syntax checker 8.1
        uses: prestashop/github-action-php-lint/8.1@v1
